### ISSUE TITLE
Apply scientific-python-cookiecutter retroactively?

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/olog#19]
The repo was originally made before we had our scientific-python-cookiecutter. It's a single-module project at present (`olog.py`) as opposed to a package with an `__init__.py`, which means it is not compatible with `versioneer`. I seems likely to grow at least one more module (see #18) so it might make sense to convert it into a package with the structure:

```
olog/
    __init__.py  # empty file
    httpx_client.py
    requests_client.py  # to be added in #18 
```

and then to add all the files from scientific-python-cookiecutter.

**Comment by ke-zhang-rd** [comment]
This is closed by #21
