### ISSUE TITLE
Should the argument to get_logs be keyword-only?

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/olog#23]
This signature

https://github.com/NSLS-II/olog/blob/a04f1055df76c3ce62f84e31eea37180bab33b67/olog/httpx_client.py#L95-L97

may be a good first for keyword-only arguments because

* There are many parameters.
* Their order is arbitrary; there is no natural or "obvious" sorting.
* It seems possible that more parameters could be added by olog-es in the future.

**Comment by ke-zhang-rd** [comment]
sounds good

**Comment by ke-zhang-rd** [comment]
closed by #25
